# Generated by Django 4.2.7 on 2023-12-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_ordermodel_city_remove_ordermodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customer.profile'),
        ),
    ]
